development:
  adapter: postgresql
  encoding: unicode
  database: tree_house_development
  pool: 5
  username: mthomson
  password: ENV['DATABASE_PASSWORD']

test:
  adapter: postgresql
  encoding: unicode
  database: tree_house_testing
  pool: 5
  username: mthomson
  password: ENV['DATABASE_PASSWORD']

production:
  adapter: postgresql
  encoding: unicode
  database: tree_house_production
  username: mthomson
  password: ENV['DATABASE_PASSWORD']
